apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nerc-restricted-with-sys-admin
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - nerc-restricted-with-sys-admin
  verbs:
  - use
